version: '3'
services: 
  lamp: 
    build: .
    restart: always
    container_name: lamp
    ports:
      - "5001:80"
    volumes: 
      - .:/app
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
