version: '3'
services: 

  dev: 
    build: .
    restart: always
    container_name: dev
    ports:
      - "5100:80"
    expose:
      - 80
    volumes: 
      - ./site:/app
      - .:/code
      - ./run.sh:/run.sh
      - dev_mysqldata:/var/lib/mysql

volumes:
  dev_mysqldata:
