version: '3'
services: 
  china: 
    build: .
    restart: always
    container_name: china
    ports:
      - "5000:80"
    volumes: 
      - ./site:/app
      - .:/code
      - ./run.sh:/run.sh
      - mysql_data:/var/lib/mysql
  india:
    build: .
    restart: always
    container_name: india
    ports:
      - "5002:80"
    volumes:
      - ./site:/app
      - .:/code
      - ./run.sh:/run.sh
      - mysql_data:/var/lib/mysql
 nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf/:etc/nginx/nginx.conf
    expose:
      - 80      
volumes:
  mysql_data:
