version: '3'
services: 
  lamp: 
    build: .
    restart: always
    container_name: lamp
    ports:
      - "5001:80"
    volumes: 
      - ./site:/app
      - .:/code
      - ./run.sh:/run.sh
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
